# Generated by Django 4.0 on 2023-11-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailResetPassword",
            fields=[
                (
                    "emailverification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.emailverification",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "userkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
            bases=("users.emailverification",),
        ),
    ]
