# Generated by Django 4.0 on 2023-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
